export const recomendations=[
    {
        "id": "2f3e4d5c-6e7d-8c9b-0f1a",
        "category": {"id": "123", "name": "Electronics"},
        "isFavorite":false,
        "price":"1500",
        "oldPrice":"1900",
        "sellerId": "1d2e3f4g-5h6i-7j8k-9l0m",
        "mediaLinks": "[{\"type\":\"img\",\"url\":\"https://telefon.kg/image/cache/catalog/new/Phones/Apple/Iphone%2011%20Pro%20Max/green/1-500x400.jpg\"},{\"type\":\"img\",\"url\":\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQL2-ePAniFthAJaQQ4gn6hdPISgAS9MnDfeKAlYLIc6A&s\"},{\"type\":\"img\",\"url\":\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2AjnePDTNwTvZ8Lzy9Y73DVIA-2qxBS2vP62p7LDG5w&s\"}]",
        "title": "Apple iPhone 11 Pro Max - 256GB, Серый космос",
        "description": "<p>Apple iPhone 11 Pro Max - один из самых мощных и технологически продвинутых смартфонов на рынке. С 6,5-дюймовым Super Retina XDR дисплеем, трехкамерной системой и процессором A13 Bionic, этот телефон идеально подходит как для профессионалов, так и для обычных пользователей. Особенности включают улучшенную систему Face ID, ночной режим фотографии и долгое время автономной работы.</p>",
        "rating": 4.8,
        "orders": 500,
        "reviews": [
            {
                "id": "rev1",
                "userId": "user123",
                "orderId": "ord1",
                "type":"review",
                "grade": 5,
                "options": "{\"color\":\"Серый космос\",\"storage\":\"256GB\"}",
                "text": "Превосходный телефон! Камера и экран просто великолепны.",
                "images": "[\"http://example.com/review_image1.jpg\"]",
                "reviewDate": "2024-05-01T12:00:00Z",
                "updatedDate": "2024-05-01T12:00:00Z",
                "likes": 10,
                "dislikes": 1,
                "comments": [
                    {
                        "id": "com1",
                        "userId": "user234",
                        "productId": "2f3e4d5c-6e7d-8c9b-0f1a",
                        "type": "comment",
                        "text": "Полностью согласен!",
                        "likes": 5,
                        "dislikes": 0,
                        "commentDate": "2024-05-02T12:00:00Z",
                        "updatedDate": "2024-05-02T12:00:00Z",
                        "comments":[]
                    }
                ]
            },
            {
                "id": "rev2",
                "userId": "user456",
                "orderId": "ord2",
                "type":"review",
                "grade": 4,
                "options": "{\"color\":\"Серый космос\",\"storage\":\"256GB\"}",
                "text": "Отличный телефон, но аккумулятор мог бы быть лучше.",
                "images": "[]",
                "reviewDate": "2024-05-03T12:00:00Z",
                "updatedDate": "2024-05-03T12:00:00Z",
                "likes": 7,
                "dislikes": 2,
                "comments": []
            }
        ],
        "options": "[{\"title\":\"цвет\",\"value\":[{\"title\":\"серый космос\",\"icon\":\"http://example.com/gray_icon.jpg\"},{\"title\":\"золотой\",\"icon\":\"http://example.com/gold_icon.jpg\"},{\"title\":\"зеленый\",\"icon\":\"http://example.com/green_icon.jpg\"}]},{\"title\":\"объем памяти\",\"value\":[{\"title\":\"64GB\",\"icon\":\"\"},{\"title\":\"256GB\",\"icon\":\"\"},{\"title\":\"512GB\",\"icon\":\"\"}]},{\"title\":\"план защиты\",\"value\":[{\"title\":\"1 год\",\"icon\":\"\"},{\"title\":\"2 года\",\"icon\":\"\"},{\"title\":\"3 года\",\"icon\":\"\"}]}]",
        "specs": "[{\"title\":\"Процессор\",\"value\":\"A13 Bionic\"},{\"title\":\"Дисплей\",\"value\":\"6.5 дюймов Super Retina XDR\"},{\"title\":\"Камера\",\"value\":\"Тройная камера 12 МП\"},{\"title\":\"Батарея\",\"value\":\"3969 мАч\"},{\"title\":\"Операционная система\",\"value\":\"iOS 14\"}]",
        "stock": 50,
        "promotions": "[{\"type\":\"points for review\",\"title\":\"баллы за отзыв\",\"value\":\"500\"}]",
        "deliveryDays": 3,
        "createdDate": "2024-05-18",
        "updatedDate": "2024-05-18"
    },
    {
        "id": "3f4e5d6c-7e8d-9c0b-1f2a",
        "category": {"id": "124", "name": "Fashion"},
        "isFavorite":false,
        "price":"1580",
        "oldPrice":"1990",
        "sellerId": "2d3e4f5g-6h7i-8j9k-0l1m",
        "mediaLinks": "[{\"type\":\"img\",\"url\":\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2SK3hOsm5ZtT9v3Bk1ZIicupTQsWEPDu-GykIG03HEQ&s\"},{\"type\":\"img\",\"url\":\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRH8uRMyMS1QgxKDOIPkufR-79U9akaY6sv6Y0_Ckhrxw&s\"}]",
        "title": "Рюкзак XD Design Bobby - Противоугонный, Водоотталкивающий, Серый",
        "description": "<p>Рюкзак XD Design Bobby - это идеальный городской рюкзак для безопасного и комфортного передвижения. Он оснащен противоугонной системой, водоотталкивающим покрытием и множеством удобных карманов. С ним вы можете быть уверены в безопасности своих вещей, будь то в путешествии или в повседневной жизни. Рюкзак также имеет отделение для ноутбука и USB-порт для зарядки устройств на ходу.</p>",
        "rating": 4.7,
        "orders": 300,
        "reviews": [
            {
                "id": "rev3",
                "userId": "user567",
                "orderId": "ord3",
                "type":"review",
                "grade": 5,
                "options": "{\"color\":\"Серый\",\"size\":\"Средний\"}",
                "text": "Очень удобный и стильный рюкзак. Отличная защита от краж.",
                "images": "[\"http://example.com/review_image2.jpg\"]",
                "reviewDate": "2024-04-20T12:00:00Z",
                "updatedDate": "2024-04-20T12:00:00Z",
                "likes": 12,
                "dislikes": 0,
                "comments": [
                    {
                        "id": "com2",
                        "userId": "user678",
                        "productId": "3f4e5d6c-7e8d-9c0b-1f2a",
                        "type": "comment",
                        "text": "Согласен, рюкзак супер!",
                        "likes": 3,
                        "dislikes": 0,
                        "commentDate": "2024-04-21T12:00:00Z",
                        "updatedDate": "2024-04-21T12:00:00Z",
                        "comments":[]
                    }
                ]
            },
            {
                "id": "rev4",
                "userId": "user789",
                "orderId": "ord4",
                "type":"review",
                "grade": 4,
                "options": "{\"color\":\"Серый\",\"size\":\"Средний\"}",
                "text": "Хороший рюкзак, но мне не хватает карманов внутри.",
                "images": "[]",
                "reviewDate": "2024-04-22T12:00:00Z",
                "updatedDate": "2024-04-22T12:00:00Z",
                "likes": 5,
                "dislikes": 1,
                "comments": []
            }
        ],
        "options": "[{\"title\":\"цвет\",\"value\":[{\"title\":\"серый\",\"icon\":\"http://example.com/gray_icon.jpg\"},{\"title\":\"черный\",\"icon\":\"http://example.com/black_icon.jpg\"},{\"title\":\"синий\",\"icon\":\"http://example.com/blue_icon.jpg\"}]},{\"title\":\"размер\",\"value\":[{\"title\":\"маленький\",\"icon\":\"\"},{\"title\":\"средний\",\"icon\":\"\"},{\"title\":\"большой\",\"icon\":\"\"}]},{\"title\":\"тип\",\"value\":[{\"title\":\"классический\",\"icon\":\"\"},{\"title\":\"премиум\",\"icon\":\"\"},{\"title\":\"путешественник\",\"icon\":\"\"}]}]",
        "specs": "[{\"title\":\"Материал\",\"value\":\"Полиэстер\"},{\"title\":\"Водоотталкивающее покрытие\",\"value\":\"Да\"},{\"title\":\"Объем\",\"value\":\"18 литров\"},{\"title\":\"Отделение для ноутбука\",\"value\":\"До 15.6 дюймов\"},{\"title\":\"Вес\",\"value\":\"850 грамм\"}]",
        "stock": 100,
        "promotions": "[{\"type\":\"discount\",\"title\":\"летняя распродажа\",\"value\":\"15% off\"}]",
        "deliveryDays": 5,
        "createdDate": "2024-04-18",
        "updatedDate": "2024-05-18"
    },
    {
        "id": "3f4e5d6c-7e8d-9c0b-2f3a",
        "category": {"id": "124", "name": "Электроника"},
        "isFavorite": false,
        "price": "55000",
        "oldPrice": "65000",
        "sellerId": "2d3e4f5g-6h7i-8j9k-1l2m",
        "mediaLinks": "[{\"type\":\"img\",\"url\":\"https://p3-ofp.static.pub/fes/cms/2022/12/07/m0521vlcnt1r2d29a50yjx8dagm5ve573937.png\"},{\"type\":\"img\",\"url\":\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqF4WuV9W64JCOoyg8qabd1jEaQyaAqYV9RQuQY5DUWA&s\"}]",
        "title": "Ноутбук Lenovo IdeaPad 5 Pro",
        "description": "<p>Мощный ноутбук Lenovo IdeaPad 5 Pro с процессором Intel Core i7, диагональю экрана 15.6 дюймов и разрешением Full HD. Идеально подходит для работы, учебы и развлечений.</p>",
        "rating": 4.8,
        "orders": 500,
        "reviews": [
            {
              "id": "rev1",
              "userId": "user123",
              "orderId": "ord1",
              "type": "review",
              "grade": 5,
              "options": "{\"color\":\"Серый\",\"size\":\"S\"}",
              "text": "Отличный ноутбук! Быстрая доставка, качественный товар.",
              "images": "[\"https://example.com/review_image1.jpg\",\"https://example.com/review_image2.jpg\"]",
              "reviewDate": "2024-05-20T12:00:00Z",
              "updatedDate": "2024-05-20T12:00:00Z",
              "likes": 10,
              "dislikes": 0,
              "comments": [
                {
                  "id": "com1",
                  "userId": "user456",
                  "productId": "3f4e5d6c-7e8d-9c0b-1f2a",
                  "type": "comment",
                  "text": "Согласен, ноутбук отличный!",
                  "likes": 2,
                  "dislikes": 0,
                  "commentDate": "2024-05-21T12:00:00Z",
                  "updatedDate": "2024-05-21T12:00:00Z",
                  "comments": []
                }
              ]
            },
            {
              "id": "rev2",
              "userId": "user456",
              "orderId": "ord2",
              "type": "review",
              "grade": 4,
              "options": "{\"color\":\"Черный\",\"size\":\"M\"}",
              "text": "Хороший ноутбук за свою цену.",
              "images": "[]",
              "reviewDate": "2024-05-22T12:00:00Z",
              "updatedDate": "2024-05-22T12:00:00Z",
              "likes": 5,
              "dislikes": 1,
              "comments": []
            }
          ],          
        "options": "[{\"title\":\"Цвет\",\"value\":[{\"title\":\"Серый\",\"icon\":\"http://example.com/gray_icon.jpg\"},{\"title\":\"Черный\",\"icon\":\"http://example.com/black_icon.jpg\"},{\"title\":\"Синий\",\"icon\":\"http://example.com/blue_icon.jpg\"}]},{\"title\":\"Память\",\"value\":[{\"title\":\"8GB RAM\",\"icon\":\"\"},{\"title\":\"16GB RAM\",\"icon\":\"\"},{\"title\":\"32GB RAM\",\"icon\":\"\"}]},{\"title\":\"Хранение\",\"value\":[{\"title\":\"256GB SSD\",\"icon\":\"\"},{\"title\":\"512GB SSD\",\"icon\":\"\"},{\"title\":\"1TB HDD\",\"icon\":\"\"}]}]",
        "specs": "[{\"title\":\"Процессор\",\"value\":\"Intel Core i7\"},{\"title\":\"Экран\",\"value\":\"15.6 дюймов, Full HD\"},{\"title\":\"Операционная система\",\"value\":\"Windows 10\"},{\"title\":\"Вес\",\"value\":\"1.8 кг\"}]",
        "stock": 50,
        "promotions": "[{\"type\":\"discount\",\"title\":\"Специальное предложение\",\"value\":\"10% скидка\"}]",
        "deliveryDays": 3,
        "createdDate": "2024-05-10",
        "updatedDate": "2024-05-18"
      },
      {
        "id": "5g6h7i8j-9k0l-1m2n-3o4p",
        "category": {"id": "456", "name": "Аксессуары"},
        "isFavorite": false,
        "price": "3500",
        "oldPrice": "3599",
        "sellerId": "4o5p6q7r-8s9t-0u1v-2w3x",
        "mediaLinks": "[{\"type\":\"img\",\"url\":\"https://cdn.photofunia.com/effects/travelers-suitcase/icons/huge.jpg\"},{\"type\":\"img\",\"url\":\"https://cdn.photofunia.com/effects/travelers-suitcase/examples/s931vb_o.jpg\"}]",
        "title": "Чемодан 'Путешественник'",
        "description": "<p>Прочный и надежный чемодан для путешествий, сделанный из качественных материалов. Идеально подходит для дальних и ближних поездок. Объем чемодана - 90 литров.</p>",
        "rating": 4.2,
        "orders": 150,
        "reviews": [
            {
              "id": "rev3",
              "userId": "user789",
              "orderId": "ord3",
              "type": "review",
              "grade": 5,
              "options": "{\"color\":\"Черный\",\"size\":\"Большой\"}",
              "text": "Отличный чемодан! Прочный и вместительный. Очень удобно путешествовать с ним.",
              "images": "[\"https://example.com/suitcase_review_image1.jpg\",\"https://example.com/suitcase_review_image2.jpg\"]",
              "reviewDate": "2024-05-25T12:00:00Z",
              "updatedDate": "2024-05-25T12:00:00Z",
              "likes": 8,
              "dislikes": 0,
              "comments": [
                {
                  "id": "com1",
                  "userId": "user123",
                  "productId": "5g6h7i8j-9k0l-1m2n-3o4p",
                  "type": "comment",
                  "text": "Согласен, у меня такой же! Очень доволен.",
                  "likes": 3,
                  "dislikes": 0,
                  "commentDate": "2024-05-26T12:00:00Z",
                  "updatedDate": "2024-05-26T12:00:00Z",
                  "comments": []
                }
              ]
            },
            {
              "id": "rev4",
              "userId": "user456",
              "orderId": "ord4",
              "type": "review",
              "grade": 4,
              "options": "{\"color\":\"Серебристый\",\"size\":\"Средний\"}",
              "text": "Хороший чемодан за свои деньги. Подошел для моих нужд.",
              "images": "[]",
              "reviewDate": "2024-05-28T12:00:00Z",
              "updatedDate": "2024-05-28T12:00:00Z",
              "likes": 6,
              "dislikes": 2,
              "comments": []
            }
          ]
          ,
        "options": "[{\"title\":\"Цвет\",\"value\":[{\"title\":\"Черный\",\"icon\":\"\"},{\"title\":\"Темно-синий\",\"icon\":\"\"},{\"title\":\"Серебристый\",\"icon\":\"\"}]},{\"title\":\"Размер\",\"value\":[{\"title\":\"Малый\",\"icon\":\"\"},{\"title\":\"Средний\",\"icon\":\"\"},{\"title\":\"Большой\",\"icon\":\"\"}]},{\"title\":\"Материал\",\"value\":[{\"title\":\"Поликарбонат\",\"icon\":\"\"},{\"title\":\"Алюминий\",\"icon\":\"\"},{\"title\":\"ABS-пластик\",\"icon\":\"\"}]}]",
        "specs": "[{\"title\":\"Вместимость\",\"value\":\"90 л\"},{\"title\":\"Вес\",\"value\":\"4.5 кг\"},{\"title\":\"Ручка\",\"value\":\"Телескопическая\"},{\"title\":\"Замок\",\"value\":\"Кодовый замок\"}]",
        "stock": 100,
        "promotions": "[{\"type\":\"discount\",\"title\":\"Осенняя распродажа\",\"value\":\"20% скидка\"}]",
        "deliveryDays": 7,
        "createdDate": "2024-05-15",
        "updatedDate": "2024-05-18"
      },
      {
        "id": "1a2b3c4d-5e6f-7g8h-9i0j",
        "category": {"id": "124", "name": "Электроника"},
        "isFavorite": false,
        "price": "79990",
        "oldPrice": "84990",
        "sellerId": "8i9j0k1l-2m3n-4o5p-6q7r",
        "mediaLinks": "[{\"type\":\"img\",\"url\":\"https://myphone.kg/files/media/19/19669.png\"},{\"type\":\"img\",\"url\":\"https://login.kg/image/cache/catalog/new/Phones/Samsung/S22%205G/samsung-galaxy-s22-5g-2-1200x800.jpg\"}]",
        "title": "Смартфон Samsung Galaxy S22",
        "description": "<p>Новый смартфон Samsung Galaxy S22 с инновационным экраном, мощным процессором и продвинутой камерой. Подходит для профессионального использования и повседневных задач.</p>",
        "rating": 4.9,
        "orders": 1000,
        "reviews": [
          {
            "id": "rev5",
            "userId": "user789",
            "orderId": "ord5",
            "type": "review",
            "grade": 5,
            "options": "{\"color\":\"Серебристый\",\"storage\":\"256GB\"}",
            "text": "Отличный смартфон! Превосходный экран и камера.",
            "images": "[\"https://example.com/s22_review_image1.jpg\"]",
            "reviewDate": "2024-05-30T12:00:00Z",
            "updatedDate": "2024-05-30T12:00:00Z",
            "likes": 15,
            "dislikes": 0,
            "comments": []
          }
        ],
        "options": "[{\"title\":\"Цвет\",\"value\":[{\"title\":\"Серый\",\"icon\":\"\"},{\"title\":\"Белый\",\"icon\":\"\"},{\"title\":\"Розовый\",\"icon\":\"\"}]},{\"title\":\"Память\",\"value\":[{\"title\":\"128GB\",\"icon\":\"\"},{\"title\":\"256GB\",\"icon\":\"\"},{\"title\":\"512GB\",\"icon\":\"\"}]}]",
        "specs": "[{\"title\":\"Процессор\",\"value\":\"Exynos 2200\"},{\"title\":\"Экран\",\"value\":\"6.5 дюймов, Dynamic AMOLED\"},{\"title\":\"Операционная система\",\"value\":\"Android 13\"},{\"title\":\"Вес\",\"value\":\"175 грамм\"}]",
        "stock": 300,
        "promotions": "[{\"type\":\"discount\",\"title\":\"Специальное предложение\",\"value\":\"10% скидка\"}]",
        "deliveryDays": 3,
        "createdDate": "2024-05-25",
        "updatedDate": "2024-05-30"
      },
      {
        "id": "3b4c5d6e-7f8g-9h0i-1j2k",
        "category": {"id": "456", "name": "Кухонная техника"},
        "isFavorite": false,
        "price": "69990",
        "oldPrice": "",
        "sellerId": "3k4l5m6n-7o8p-9q0r-1s2t",
        "mediaLinks": "[{\"type\":\"img\",\"url\":\"https://delonghi-shop.com.ua/modules/images/delonghi_magnifica_esam_4000b_a.jpg\"},{\"type\":\"img\",\"url\":\"https://www.banan.kg/u/images/8285/1180558_1176406_xxl.jpg\"}]",
        "title": "Кофемашина DeLonghi Magnifica",
        "description": "<p>Компактная кофемашина DeLonghi Magnifica с автоматической системой приготовления кофе. Подходит для приготовления как эспрессо, так и капучино.</p>",
        "rating": 4.6,
        "orders": 500,
        "reviews": [
          {
            "id": "rev6",
            "userId": "user234",
            "orderId": "ord6",
            "type": "review",
            "grade": 5,
            "options": "{\"color\":\"Серебристый\"}",
            "text": "Отличная кофемашина! Вкусный кофе и простое управление.",
            "images": "[\"https://example.com/magnifica_review_image1.jpg\"]",
            "reviewDate": "2024-05-31T12:00:00Z",
            "updatedDate": "2024-05-31T12:00:00Z",
            "likes": 12,
            "dislikes": 0,
            "comments": []
          }
        ],
        "options": "[{\"title\":\"Цвет\",\"value\":[{\"title\":\"Черный\",\"icon\":\"\"},{\"title\":\"Серебристый\",\"icon\":\"\"},{\"title\":\"Белый\",\"icon\":\"\"}]},{\"title\":\"Мощность\",\"value\":[{\"title\":\"1450 Вт\",\"icon\":\"\"}]}]",
        "specs": "[{\"title\":\"Процессор\",\"value\":\"Exynos 2200\"},{\"title\":\"Экран\",\"value\":\"6.5 дюймов, Dynamic AMOLED\"},{\"title\":\"Операционная система\",\"value\":\"Android 13\"},{\"title\":\"Вес\",\"value\":\"175 грамм\"}]",
        "stock": 300,
        "promotions": "[{\"type\":\"discount\",\"title\":\"Специальное предложение\",\"value\":\"10% скидка\"}]",
        "deliveryDays": 3,
        "createdDate": "2024-05-25",
        "updatedDate": "2024-05-30"
    }
]
